# Generated by Django 5.2.3 on 2025-07-03 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('pullup_type', models.CharField(choices=[('PU', 'Pullups'), ('CH', 'Chinups'), ('NE', 'Neutral')], default='PU', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField(choices=[(1, 'Set 1'), (2, 'Set 2'), (3, 'Set 3')])),
                ('pullup_count', models.PositiveIntegerField(default=0)),
                ('pushup_count', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workoutlog.workoutsession')),
            ],
            options={
                'ordering': ['session', 'set_number'],
                'unique_together': {('session', 'set_number')},
            },
        ),
    ]
