# Generated by Django 5.2.3 on 2025-07-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='pullup_count1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='pullup_count2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='pullup_count3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='pushup_count1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='pushup_count2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='pushup_count3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='WorkoutSet',
        ),
    ]
