# Generated by Django 5.2.3 on 2025-07-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutlog', '0002_workoutsession_pullup_count1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='total_pullups',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='total_pushups',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
