# Generated by Django 5.2.3 on 2025-07-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutlog', '0003_workoutsession_total_pullups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='date',
            field=models.DateField(),
        ),
    ]
